// Generated by https://quicktype.io

export interface APIRefResponse {
  refs: Ref[];
  integrationFieldsRef: null;
  bookmarks: Bookmarks;
  types: Types;
  languages: Language[];
  tags: string[];
  forms: Forms;
  oauth_initiate: string;
  oauth_token: string;
  version: string;
  experiments: Experiments;
  license: string;
}

interface Bookmarks {}

interface Experiments {
  draft: any[];
  running: any[];
}

interface Forms {
  everything: Everything;
  tags: Tags;
}

interface Everything {
  method: string;
  enctype: string;
  action: string;
  fields: Fields;
}

interface Fields {
  ref: After;
  q: After;
  lang: After;
  page: Page;
  pageSize: Page;
  after: After;
  fetch: After;
  fetchLinks: After;
  graphQuery: After;
  orderings: After;
  referer: After;
}

interface After {
  type: string;
  multiple: boolean;
}

interface Page {
  type: string;
  multiple: boolean;
  default: string;
}

interface Tags {
  method: string;
  enctype: string;
  action: string;
  fields: Bookmarks;
}

interface Language {
  id: string;
  name: string;
}

interface Ref {
  id: string;
  ref: string;
  label: string;
  isMasterRef: boolean;
}

interface Types {
  product: string;
  category: string;
  banner: string;
}
